create or replace table data_budget_common_expend_belanja_subkegiatan (
	id                            varchar(255)   not null,
	skpd_id                       varchar(22)    not null,
	unit_id                       varchar(22)    not null,
	urusan_id                     varchar(1)     not null,
	bidang_id                     varchar(4)     not null,
	program_id                    varchar(7)     not null,
	program_code                  varchar(7)     not null,
	kegiatan_id                   varchar(12)    not null,
	kegiatan_code                 varchar(12)    not null,
	subkegiatan_id                varchar(17)    not null,
	subkegiatan_code              varchar(17)    not null,
	fungsi_id                     varchar(2)     not null,
	subfungsi_id                  varchar(5)     not null,
	belanja_operasi               decimal(38, 2) not null,
	belanja_modal                 decimal(38, 2) not null,
	belanja_tidak_terduga         decimal(38, 2) not null,
	belanja_transfer              decimal(38, 2) not null,
	total                         decimal(38, 2) not null,
	belanja_operasi_sebelum       decimal(38, 2) not null,
	belanja_modal_sebelum         decimal(38, 2) not null,
	belanja_tidak_terduga_sebelum decimal(38, 2) not null,
	belanja_transfer_sebelum      decimal(38, 2) not null,
	sebelum                       decimal(38, 2) not null,
	created_at                    datetime       null,
	created_by                    varchar(18)    null,
	updated_at                    datetime       null,
	updated_by                    varchar(18)    null,
	is_deleted                    bit            null,
	deleted_at                    datetime       null,
	deleted_by                    varchar(18)    null,
	is_locked                     bit            null,
	locked_at                     datetime       null,
	locked_by                     varchar(18)    null,
	is_rincian_locked             bit            null,
	rincian_locked_at             datetime       null,
	rincian_locked_by             varchar(18)    null,
	constraint ck_data_budget_common_expend_belanja_subkegiatan_01 check (id = concat_ws('|', unit_id, bidang_id, subkegiatan_id)),
	constraint ck_data_budget_common_expend_belanja_subkegiatan_02 check (sebelum = belanja_operasi_sebelum + belanja_modal_sebelum + belanja_tidak_terduga_sebelum + belanja_transfer_sebelum),
	constraint ck_data_budget_common_expend_belanja_subkegiatan_03 check (total = belanja_operasi + belanja_modal + belanja_tidak_terduga + belanja_transfer),
	constraint ck_data_budget_common_expend_belanja_subkegiatan_04 check (program_code = if(program_id not like '0.00.01%', program_id, concat(bidang_id, substring(program_id, 5)))),
	constraint ck_data_budget_common_expend_belanja_subkegiatan_05 check (kegiatan_code = if(kegiatan_id not like '0.00.01%', kegiatan_id, concat(bidang_id, substring(kegiatan_id, 5)))),
	constraint ck_data_budget_common_expend_belanja_subkegiatan_06 check (subkegiatan_code = if(subkegiatan_id not like '0.00.01%', subkegiatan_id, concat(bidang_id, substring(subkegiatan_id, 5)))),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_01 foreign key (skpd_id) references data_master_organisasi (id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_02 foreign key (skpd_id, unit_id) references data_master_organisasi (skpd_id, unit_id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_03 foreign key (urusan_id) references data_master_urusan (id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_04 foreign key (urusan_id, bidang_id) references data_master_bidang (urusan_id, id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_05 foreign key (program_id) references data_master_program (id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_06 foreign key (fungsi_id, subfungsi_id, program_id, kegiatan_id) references data_master_kegiatan (fungsi_id, subfungsi_id, program_id, id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_07 foreign key (fungsi_id, subfungsi_id, program_id, kegiatan_id, subkegiatan_id) references data_master_subkegiatan (fungsi_id, subfungsi_id, program_id, kegiatan_id, id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_08 foreign key (fungsi_id) references data_master_fungsi (id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_09 foreign key (fungsi_id, subfungsi_id) references data_master_subfungsi (fungsi_id, id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_10 foreign key (created_by) references data_user (id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_11 foreign key (updated_by) references data_user (id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_12 foreign key (deleted_by) references data_user (id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_13 foreign key (locked_by) references data_user (id),
	constraint fk_data_budget_common_expend_belanja_subkegiatan_14 foreign key (rincian_locked_by) references data_user (id),
	primary key (id)
) engine = innodb
  charset = utf8mb4
  collate = utf8mb4_unicode_ci;