create or replace table sipd_budget_common_expend_belanja_subkegiatan (
	id               varchar(255) not null,
	unit_id          varchar(22)  not null,
	unit_code        varchar(22)  not null,
	skpd_id          varchar(22)  not null,
	skpd_code        varchar(22)  not null,
	unit_skpd_id     varchar(22)  not null,
	unit_skpd_code   varchar(22)  not null,
	urusan_id        varchar(1)   not null,
	urusan_code      varchar(1)   not null,
	bidang_id        varchar(4)   not null,
	bidang_code      varchar(4)   not null,
	program_id       varchar(7)   not null,
	program_code     varchar(7)   not null,
	kegiatan_id      varchar(12)  not null,
	kegiatan_code    varchar(12)  not null,
	subkegiatan_id   varchar(17)  not null,
	subkegiatan_code varchar(17)  not null,
	subject_id       varchar(255) not null,
	created_at       datetime     null,
	created_by       varchar(18)  null,
	updated_at       datetime     null,
	updated_by       varchar(18)  null,
	is_deleted       bit          null,
	deleted_at       datetime     null,
	deleted_by       varchar(18)  null,
	constraint fk_sipd_budget_common_expend_belanja_subkegiatan_01 foreign key (subject_id) references data_budget_common_expend_belanja_subkegiatan (id),
	constraint fk_sipd_budget_common_expend_belanja_subkegiatan_02 foreign key (created_by) references data_user (id),
	constraint fk_sipd_budget_common_expend_belanja_subkegiatan_03 foreign key (updated_by) references data_user (id),
	constraint fk_sipd_budget_common_expend_belanja_subkegiatan_04 foreign key (deleted_by) references data_user (id),
	primary key (id)
) engine = innodb
  charset = utf8mb4
  collate = utf8mb4_unicode_ci;