create or replace table data_budget_common_expend_belanja_rincian (
	id               bigint         not null,
	skpd_id          varchar(22)    not null,
	unit_id          varchar(22)    not null,
	urusan_id        varchar(1)     not null,
	bidang_id        varchar(4)     not null,
	program_id       varchar(7)     not null,
	program_code     varchar(7)     not null,
	kegiatan_id      varchar(12)    not null,
	kegiatan_code    varchar(12)    not null,
	subkegiatan_id   varchar(17)    not null,
	subkegiatan_code varchar(17)    not null,
	fungsi_id        varchar(2)     not null,
	subfungsi_id     varchar(5)     not null,
	rekening1_id     varchar(1)     not null,
	rekening2_id     varchar(3)     not null,
	rekening3_id     varchar(6)     not null,
	rekening4_id     varchar(9)     not null,
	rekening5_id     varchar(12)    not null,
	rekening6_id     varchar(17)    not null,
	sumber_id        varchar(17)    null,
	jenis            varchar(255)   null,
	penerima         varchar(255)   null,
	description      varchar(255)   null,
	information      varchar(255)   null,
	volume1          decimal(38, 2) null,
	satuan1          varchar(255)   null,
	volume2          decimal(38, 2) null,
	satuan2          varchar(255)   null,
	volume3          decimal(38, 2) null,
	satuan3          varchar(255)   null,
	volume4          decimal(38, 2) null,
	satuan4          varchar(255)   null,
	volume           decimal(38, 2) null,
	satuan           varchar(255)   null,
	price            decimal(38, 2) null,
	total            decimal(38, 2) not null,
	sebelum          decimal(38, 2) not null,
	created_at       datetime       null,
	created_by       varchar(18)    null,
	updated_at       datetime       null,
	updated_by       varchar(18)    null,
	is_deleted       bit            null,
	deleted_at       datetime       null,
	deleted_by       varchar(18)    null,
	constraint ck_data_budget_common_expend_belanja_rincian_01 check (program_code = if(program_id not like '0.00.01%', program_id, concat(bidang_id, substring(program_id, 5)))),
	constraint ck_data_budget_common_expend_belanja_rincian_02 check (kegiatan_code = if(kegiatan_id not like '0.00.01%', kegiatan_id, concat(bidang_id, substring(kegiatan_id, 5)))),
	constraint ck_data_budget_common_expend_belanja_rincian_03 check (subkegiatan_code = if(subkegiatan_id not like '0.00.01%', subkegiatan_id, concat(bidang_id, substring(subkegiatan_id, 5)))),
	constraint fk_data_budget_common_expend_belanja_rincian_01 foreign key (rekening1_id) references data_master_belanja1 (id),
	constraint fk_data_budget_common_expend_belanja_rincian_02 foreign key (rekening1_id, rekening2_id) references data_master_belanja2 (rekening1_id, id),
	constraint fk_data_budget_common_expend_belanja_rincian_03 foreign key (rekening1_id, rekening2_id, rekening3_id) references data_master_belanja3 (rekening1_id, rekening2_id, id),
	constraint fk_data_budget_common_expend_belanja_rincian_04 foreign key (rekening1_id, rekening2_id, rekening3_id, rekening4_id) references data_master_belanja4 (rekening1_id, rekening2_id, rekening3_id, id),
	constraint fk_data_budget_common_expend_belanja_rincian_05 foreign key (rekening1_id, rekening2_id, rekening3_id, rekening4_id, rekening5_id) references data_master_belanja5 (rekening1_id, rekening2_id, rekening3_id, rekening4_id, id),
	constraint fk_data_budget_common_expend_belanja_rincian_06 foreign key (rekening1_id, rekening2_id, rekening3_id, rekening4_id, rekening5_id, rekening6_id) references data_master_belanja6 (rekening1_id, rekening2_id, rekening3_id, rekening4_id, rekening5_id, id),
	constraint fk_data_budget_common_expend_belanja_rincian_07 foreign key (sumber_id) references data_master_sumber (id),
	constraint fk_data_budget_common_expend_belanja_rincian_08 foreign key (skpd_id) references data_master_organisasi (id),
	constraint fk_data_budget_common_expend_belanja_rincian_09 foreign key (skpd_id, unit_id) references data_master_organisasi (skpd_id, unit_id),
	constraint fk_data_budget_common_expend_belanja_rincian_10 foreign key (urusan_id) references data_master_urusan (id),
	constraint fk_data_budget_common_expend_belanja_rincian_11 foreign key (urusan_id, bidang_id) references data_master_bidang (urusan_id, id),
	constraint fk_data_budget_common_expend_belanja_rincian_12 foreign key (program_id) references data_master_program (id),
	constraint fk_data_budget_common_expend_belanja_rincian_13 foreign key (fungsi_id, subfungsi_id, program_id, kegiatan_id) references data_master_kegiatan (fungsi_id, subfungsi_id, program_id, id),
	constraint fk_data_budget_common_expend_belanja_rincian_14 foreign key (fungsi_id, subfungsi_id, program_id, kegiatan_id, subkegiatan_id) references data_master_subkegiatan (fungsi_id, subfungsi_id, program_id, kegiatan_id, id),
	constraint fk_data_budget_common_expend_belanja_rincian_15 foreign key (fungsi_id) references data_master_fungsi (id),
	constraint fk_data_budget_common_expend_belanja_rincian_16 foreign key (fungsi_id, subfungsi_id) references data_master_subfungsi (fungsi_id, id),
	constraint fk_data_budget_common_expend_belanja_rincian_17 foreign key (created_by) references data_user (id),
	constraint fk_data_budget_common_expend_belanja_rincian_18 foreign key (updated_by) references data_user (id),
	constraint fk_data_budget_common_expend_belanja_rincian_19 foreign key (deleted_by) references data_user (id),
	primary key (id)
) engine = innodb
  charset = utf8mb4
  collate = utf8mb4_unicode_ci;