package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pendapatan_lo.pendapatan_lo1;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo1.DataMasterRekeningPendapatanLo1;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pendapatan_lo.pendapatan_lo1.DataMasterRekeningPendapatanLo1Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo1.DataMasterRekeningPendapatanLo1Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening1.AbstractDataMasterRekening1Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening1.DataMasterRekening1JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class DataMasterRekeningPendapatanLo1RepositoryImpl extends AbstractDataMasterRekening1Repository<DataMasterRekeningPendapatanLo1Entity, DataMasterRekeningPendapatanLo1> implements DataMasterRekeningPendapatanLo1Repository {

	private final DataMasterRekeningPendapatanLo1JpaRepository repository;

	@Override
	protected DataMasterRekening1JpaRepository<DataMasterRekeningPendapatanLo1Entity, DataMasterRekeningPendapatanLo1> repositoryOfMasterRekening() {
		return this.repository;
	}

}