package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pembiayaan.pembiayaan2;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan2.DataMasterRekeningPembiayaan2;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan2.SipdMasterRekeningPembiayaan2;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pembiayaan.pembiayaan2.SipdMasterRekeningPembiayaan2Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pembiayaan.pembiayaan2.SipdMasterRekeningPembiayaan2Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening2.AbstractSipdMasterRekening2Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening2.SipdMasterRekening2JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class SipdMasterRekeningPembiayaan2RepositoryImpl extends AbstractSipdMasterRekening2Repository<SipdMasterRekeningPembiayaan2Entity, SipdMasterRekeningPembiayaan2, DataMasterRekeningPembiayaan2> implements SipdMasterRekeningPembiayaan2Repository {

	private final SipdMasterRekeningPembiayaan2JpaRepository repository;

	@Override
	protected SipdMasterRekening2JpaRepository<SipdMasterRekeningPembiayaan2Entity, SipdMasterRekeningPembiayaan2, DataMasterRekeningPembiayaan2> repositoryOfMasterRekening() {
		return this.repository;
	}

}