package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pembiayaan.pembiayaan2;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan2.DataMasterRekeningPembiayaan2;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan2.SipdMasterRekeningPembiayaan2;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pembiayaan.pembiayaan2.SipdMasterRekeningPembiayaan2Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening2.SipdMasterRekening2JpaRepository;

public interface SipdMasterRekeningPembiayaan2JpaRepository extends SipdMasterRekening2JpaRepository<SipdMasterRekeningPembiayaan2Entity, SipdMasterRekeningPembiayaan2, DataMasterRekeningPembiayaan2> {

}