package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pendapatan_lo.pendapatan_lo6;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo6.DataMasterRekeningPendapatanLo6;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo6.SipdMasterRekeningPendapatanLo6;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pendapatan_lo.pendapatan_lo6.SipdMasterRekeningPendapatanLo6Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo6.SipdMasterRekeningPendapatanLo6Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening6.AbstractSipdMasterRekening6Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening6.SipdMasterRekening6JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class SipdMasterRekeningPendapatanLo6RepositoryImpl extends AbstractSipdMasterRekening6Repository<SipdMasterRekeningPendapatanLo6Entity, SipdMasterRekeningPendapatanLo6, DataMasterRekeningPendapatanLo6> implements SipdMasterRekeningPendapatanLo6Repository {

	private final SipdMasterRekeningPendapatanLo6JpaRepository repository;

	@Override
	protected SipdMasterRekening6JpaRepository<SipdMasterRekeningPendapatanLo6Entity, SipdMasterRekeningPendapatanLo6, DataMasterRekeningPendapatanLo6> repositoryOfMasterRekening() {
		return this.repository;
	}

}