package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.kewajiban.kewajiban2;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.kewajiban.kewajiban2.DataMasterRekeningKewajiban2;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.kewajiban.kewajiban2.SipdMasterRekeningKewajiban2;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.kewajiban.kewajiban2.SipdMasterRekeningKewajiban2Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening2.SipdMasterRekening2JpaRepository;

public interface SipdMasterRekeningKewajiban2JpaRepository extends SipdMasterRekening2JpaRepository<SipdMasterRekeningKewajiban2Entity, SipdMasterRekeningKewajiban2, DataMasterRekeningKewajiban2> {

}