package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pembiayaan.pembiayaan3;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan3.DataMasterRekeningPembiayaan3;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan3.SipdMasterRekeningPembiayaan3;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pembiayaan.pembiayaan3.SipdMasterRekeningPembiayaan3Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening3.SipdMasterRekening3JpaRepository;

public interface SipdMasterRekeningPembiayaan3JpaRepository extends SipdMasterRekening3JpaRepository<SipdMasterRekeningPembiayaan3Entity, SipdMasterRekeningPembiayaan3, DataMasterRekeningPembiayaan3> {

}