package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pembiayaan.pembiayaan3;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan3.DataMasterRekeningPembiayaan3;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan3.SipdMasterRekeningPembiayaan3;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pembiayaan.pembiayaan3.SipdMasterRekeningPembiayaan3Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pembiayaan.pembiayaan3.SipdMasterRekeningPembiayaan3Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening3.AbstractSipdMasterRekening3Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening3.SipdMasterRekening3JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class SipdMasterRekeningPembiayaan3RepositoryImpl extends AbstractSipdMasterRekening3Repository<SipdMasterRekeningPembiayaan3Entity, SipdMasterRekeningPembiayaan3, DataMasterRekeningPembiayaan3> implements SipdMasterRekeningPembiayaan3Repository {

	private final SipdMasterRekeningPembiayaan3JpaRepository repository;

	@Override
	protected SipdMasterRekening3JpaRepository<SipdMasterRekeningPembiayaan3Entity, SipdMasterRekeningPembiayaan3, DataMasterRekeningPembiayaan3> repositoryOfMasterRekening() {
		return this.repository;
	}

}