package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pendapatan_lo.pendapatan_lo5;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo5.DataMasterRekeningPendapatanLo5;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo5.SipdMasterRekeningPendapatanLo5;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pendapatan_lo.pendapatan_lo5.SipdMasterRekeningPendapatanLo5Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo5.SipdMasterRekeningPendapatanLo5Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening5.AbstractSipdMasterRekening5Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening5.SipdMasterRekening5JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class SipdMasterRekeningPendapatanLo5RepositoryImpl extends AbstractSipdMasterRekening5Repository<SipdMasterRekeningPendapatanLo5Entity, SipdMasterRekeningPendapatanLo5, DataMasterRekeningPendapatanLo5> implements SipdMasterRekeningPendapatanLo5Repository {

	private final SipdMasterRekeningPendapatanLo5JpaRepository repository;

	@Override
	protected SipdMasterRekening5JpaRepository<SipdMasterRekeningPendapatanLo5Entity, SipdMasterRekeningPendapatanLo5, DataMasterRekeningPendapatanLo5> repositoryOfMasterRekening() {
		return this.repository;
	}

}