package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pendapatan.pendapatan1;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan.pendapatan1.DataMasterRekeningPendapatan1;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan.pendapatan1.SipdMasterRekeningPendapatan1;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pendapatan.pendapatan1.SipdMasterRekeningPendapatan1Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pendapatan.pendapatan1.SipdMasterRekeningPendapatan1Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening1.AbstractSipdMasterRekening1Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening1.SipdMasterRekening1JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class SipdMasterRekeningPendapatan1RepositoryImpl extends AbstractSipdMasterRekening1Repository<SipdMasterRekeningPendapatan1Entity, SipdMasterRekeningPendapatan1, DataMasterRekeningPendapatan1> implements SipdMasterRekeningPendapatan1Repository {

	private final SipdMasterRekeningPendapatan1JpaRepository repository;

	@Override
	protected SipdMasterRekening1JpaRepository<SipdMasterRekeningPendapatan1Entity, SipdMasterRekeningPendapatan1, DataMasterRekeningPendapatan1> repositoryOfMasterRekening() {
		return this.repository;
	}

}