package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pendapatan.pendapatan1;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan.pendapatan1.DataMasterRekeningPendapatan1;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan.pendapatan1.SipdMasterRekeningPendapatan1;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pendapatan.pendapatan1.SipdMasterRekeningPendapatan1Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening1.SipdMasterRekening1JpaRepository;

public interface SipdMasterRekeningPendapatan1JpaRepository extends SipdMasterRekening1JpaRepository<SipdMasterRekeningPendapatan1Entity, SipdMasterRekeningPendapatan1, DataMasterRekeningPendapatan1> {

}