package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pendapatan.pendapatan4;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan.pendapatan4.DataMasterRekeningPendapatan4;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan.pendapatan4.SipdMasterRekeningPendapatan4;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pendapatan.pendapatan4.SipdMasterRekeningPendapatan4Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening4.SipdMasterRekening4JpaRepository;

public interface SipdMasterRekeningPendapatan4JpaRepository extends SipdMasterRekening4JpaRepository<SipdMasterRekeningPendapatan4Entity, SipdMasterRekeningPendapatan4, DataMasterRekeningPendapatan4> {

}