create or replace table data_user (
	id            varchar(18)  not null,
	pangkat       char(2)      not null,
	name          varchar(255) not null,
	title_prefix  varchar(255) null,
	title_suffix  varchar(255) null,
	password      varchar(255) not null,
	date_of_birth date         not null,
	date_of_start date         null,
	gender        tinyint      not null,
	number        smallint     not null,
	is_pns        bit          not null,
	is_p3k        bit          not null,
	is_locked     bit          not null,
	locked_at     datetime     null,
	locked_by     varchar(18)  null,
	created_at    datetime     null,
	created_by    varchar(18)  null,
	updated_at    datetime     null,
	updated_by    varchar(18)  null,
	is_deleted    bit          null,
	deleted_at    datetime     null,
	deleted_by    varchar(18)  null,
	constraint ck_data_user_01 check (pangkat regexp '[1-4][A-D]|4E|0[1-9]|1[0-7]'),
	constraint ck_data_user_02 check (gender between 1 and 2),
	constraint ck_data_user_03 check (number between 1 and 999),
	constraint ck_data_user_04 check (is_pns = (pangkat regexp '[1-4][A-D]|4E')),
	constraint ck_data_user_05 check (is_p3k = (pangkat regexp '0[1-9]|1[0-7]')),
	constraint fk_data_user_01 foreign key (locked_by) references data_user (id),
	constraint fk_data_user_02 foreign key (created_by) references data_user (id),
	constraint fk_data_user_03 foreign key (updated_by) references data_user (id),
	constraint fk_data_user_04 foreign key (deleted_by) references data_user (id),
	primary key (id)
) engine = innodb
  charset = utf8mb4
  collate = utf8mb4_unicode_ci;