package com.rendyrobbani.keuangan.persistence.repository.master.classification.organisasi;

import com.rendyrobbani.keuangan.persistence.entity.master.classification.organisasi.LogsMasterOrganisasiEntity;

import com.rendyrobbani.keuangan.persistence.repository.master.classification.LogsMasterClassificationJpaRepository;

public interface LogsMasterOrganisasiJpaRepository extends DataMasterClassificationJpaRepository<LogsMasterOrganisasiEntity> {}