package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.kewajiban.kewajiban5;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.kewajiban.kewajiban5.DataMasterRekeningKewajiban5;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.kewajiban.kewajiban5.SipdMasterRekeningKewajiban5;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.kewajiban.kewajiban5.SipdMasterRekeningKewajiban5Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening5.SipdMasterRekening5JpaRepository;

public interface SipdMasterRekeningKewajiban5JpaRepository extends SipdMasterRekening5JpaRepository<SipdMasterRekeningKewajiban5Entity, SipdMasterRekeningKewajiban5, DataMasterRekeningKewajiban5> {

}