package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.kewajiban.kewajiban3;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.kewajiban.kewajiban3.DataMasterRekeningKewajiban3;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.kewajiban.kewajiban3.SipdMasterRekeningKewajiban3;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.kewajiban.kewajiban3.SipdMasterRekeningKewajiban3Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening3.SipdMasterRekening3JpaRepository;

public interface SipdMasterRekeningKewajiban3JpaRepository extends SipdMasterRekening3JpaRepository<SipdMasterRekeningKewajiban3Entity, SipdMasterRekeningKewajiban3, DataMasterRekeningKewajiban3> {

}