package com.rendyrobbani.keuangan.persistence.repository.master.classification.program;

import com.rendyrobbani.keuangan.persistence.entity.master.classification.program.DataMasterProgramEntity;

import com.rendyrobbani.keuangan.persistence.repository.master.classification.DataMasterClassificationJpaRepository;

public interface DataMasterProgramJpaRepository extends DataMasterClassificationJpaRepository<DataMasterProgramEntity> {}