package com.rendyrobbani.keuangan.persistence.repository.master.classification.program;

import com.rendyrobbani.keuangan.persistence.entity.master.classification.program.SipdMasterProgramEntity;

import com.rendyrobbani.keuangan.persistence.repository.master.classification.SipdMasterClassificationJpaRepository;

public interface SipdMasterProgramJpaRepository extends SipdMasterClassificationJpaRepository<SipdMasterProgramEntity> {}