create or replace table data_master_kewajiban6 (
	id           varchar(17)  not null,
	code         varchar(17)  not null,
	name         varchar(510) not null,
	is_locked    bit          not null,
	locked_at    datetime     null,
	locked_by    varchar(18)  null,
	created_at   datetime     null,
	created_by   varchar(18)  null,
	updated_at   datetime     null,
	updated_by   varchar(18)  null,
	is_deleted   bit          null,
	deleted_at   datetime     null,
	deleted_by   varchar(18)  null,
	rekening1_id varchar(1)   not null,
	rekening2_id varchar(3)   not null,
	rekening3_id varchar(6)   not null,
	rekening4_id varchar(9)   not null,
	rekening5_id varchar(12)  not null,
	constraint ck_data_master_kewajiban6_01 check (id = code),
	constraint ck_data_master_kewajiban6_02 check (rekening1_id = left(id, length(rekening1_id))),
	constraint ck_data_master_kewajiban6_03 check (rekening2_id = left(id, length(rekening2_id))),
	constraint ck_data_master_kewajiban6_04 check (rekening3_id = left(id, length(rekening3_id))),
	constraint ck_data_master_kewajiban6_05 check (rekening4_id = left(id, length(rekening4_id))),
	constraint ck_data_master_kewajiban6_06 check (rekening5_id = left(id, length(rekening5_id))),
	constraint fk_data_master_kewajiban6_01 foreign key (rekening1_id) references data_master_kewajiban1 (id),
	constraint fk_data_master_kewajiban6_02 foreign key (rekening1_id, rekening2_id) references data_master_kewajiban2 (rekening1_id, id),
	constraint fk_data_master_kewajiban6_03 foreign key (rekening1_id, rekening2_id, rekening3_id) references data_master_kewajiban3 (rekening1_id, rekening2_id, id),
	constraint fk_data_master_kewajiban6_04 foreign key (rekening1_id, rekening2_id, rekening3_id, rekening4_id) references data_master_kewajiban4 (rekening1_id, rekening2_id, rekening3_id, id),
	constraint fk_data_master_kewajiban6_05 foreign key (rekening1_id, rekening2_id, rekening3_id, rekening4_id, rekening5_id) references data_master_kewajiban5 (rekening1_id, rekening2_id, rekening3_id, rekening4_id, id),
	constraint fk_data_master_kewajiban6_06 foreign key (locked_by) references data_user (id),
	constraint fk_data_master_kewajiban6_07 foreign key (created_by) references data_user (id),
	constraint fk_data_master_kewajiban6_08 foreign key (updated_by) references data_user (id),
	constraint fk_data_master_kewajiban6_09 foreign key (deleted_by) references data_user (id),
	constraint uk_data_master_kewajiban6_01 unique key (rekening1_id, rekening2_id, rekening3_id, rekening4_id, rekening5_id, id),
	primary key (id)
) engine = innodb
  charset = utf8mb4
  collate = utf8mb4_unicode_ci;