create or replace table data_master_sumber (
	id         varchar(17)  not null,
	code       varchar(17)  not null,
	name       varchar(510) not null,
	level      tinyint      not null,
	is_enabled bit          not null,
	is_umum    bit          not null,
	is_khusus  bit          not null,
	is_locked  bit          not null,
	locked_at  datetime     null,
	locked_by  varchar(18)  null,
	created_at datetime     null,
	created_by varchar(18)  null,
	updated_at datetime     null,
	updated_by varchar(18)  null,
	is_deleted bit          null,
	deleted_at datetime     null,
	deleted_by varchar(18)  null,
	sumber1_id varchar(1)   null,
	sumber2_id varchar(3)   null,
	sumber3_id varchar(6)   null,
	sumber4_id varchar(9)   null,
	sumber5_id varchar(12)  null,
	sumber6_id varchar(17)  null,
	constraint ck_data_master_sumber_01 check (id = code),
	constraint ck_data_master_sumber_02 check (code = coalesce(sumber6_id, sumber5_id, sumber4_id, sumber3_id, sumber2_id, sumber1_id)),
	constraint ck_data_master_sumber_03 check (level = (case when sumber6_id is not null then 6 when sumber5_id is not null then 5 when sumber4_id is not null then 4 when sumber3_id is not null then 3 when sumber2_id is not null then 2 when sumber1_id is not null then 1 end)),
	constraint ck_data_master_sumber_04 check (sumber1_id = left(id, length(sumber1_id))),
	constraint ck_data_master_sumber_05 check (sumber2_id = left(id, length(sumber2_id))),
	constraint ck_data_master_sumber_06 check (sumber3_id = left(id, length(sumber3_id))),
	constraint ck_data_master_sumber_07 check (sumber4_id = left(id, length(sumber4_id))),
	constraint ck_data_master_sumber_08 check (sumber5_id = left(id, length(sumber5_id))),
	constraint ck_data_master_sumber_09 check (sumber6_id = left(id, length(sumber6_id))),
	constraint fk_data_master_sumber_01 foreign key (locked_by) references data_user (id),
	constraint fk_data_master_sumber_02 foreign key (created_by) references data_user (id),
	constraint fk_data_master_sumber_03 foreign key (updated_by) references data_user (id),
	constraint fk_data_master_sumber_04 foreign key (deleted_by) references data_user (id),
	primary key (id)
) engine = innodb
  charset = utf8mb4
  collate = utf8mb4_unicode_ci;