create or replace table data_budget_record_organisasi (
	common_id         varchar(22)  not null,
	code              varchar(22)  not null,
	name              varchar(255) not null,
	is_skpd           bit          not null,
	is_unit           bit          not null,
	is_setda          bit          not null,
	is_skpkd          bit          not null,
	main_bidang       tinyint      not null,
	head_status       tinyint      null,
	head_pangkat      char(2)      null,
	head_name         varchar(255) null,
	head_title_prefix varchar(255) null,
	head_title_suffix varchar(255) null,
	created_at        datetime     null,
	created_by        varchar(18)  null,
	updated_at        datetime     null,
	updated_by        varchar(18)  null,
	is_deleted        bit          null,
	deleted_at        datetime     null,
	deleted_by        varchar(18)  null,
	skpd_id           varchar(22)  not null,
	unit_id           varchar(22)  not null,
	bidang1_id        varchar(4)   not null,
	bidang2_id        varchar(4)   null,
	bidang3_id        varchar(4)   null,
	head_id           varchar(22)  null,
	id                varchar(255) not null,
	jadwal_id         bigint       not null,
	constraint ck_data_budget_record_organisasi_01 check (id = concat_ws('|', jadwal_id, common_id)),
	constraint ck_data_budget_record_organisasi_02 check (common_id = code),
	constraint ck_data_budget_record_organisasi_03 check (common_id = unit_id),
	constraint ck_data_budget_record_organisasi_04 check (is_skpd is null or (is_skpd = (code like '%0000'))),
	constraint ck_data_budget_record_organisasi_05 check (is_unit is null or (is_unit = (code not like '%0000'))),
	constraint ck_data_budget_record_organisasi_06 check (is_setda is null or (is_setda = (code like '4.01%0000'))),
	constraint ck_data_budget_record_organisasi_07 check (skpd_id = concat(left(unit_id, 18), '0000')),
	constraint ck_data_budget_record_organisasi_08 check (main_bidang between 1 and 3),
	constraint ck_data_budget_record_organisasi_09 check (head_status is null or head_status between 1 and 5),
	constraint ck_data_budget_record_organisasi_10 check (head_pangkat regexp '[1-4][A-D]|4E|0[1-9]|1[0-7]'),
	constraint fk_data_budget_record_organisasi_01 foreign key (bidang1_id) references data_master_bidang (id),
	constraint fk_data_budget_record_organisasi_02 foreign key (bidang2_id) references data_master_bidang (id),
	constraint fk_data_budget_record_organisasi_03 foreign key (bidang3_id) references data_master_bidang (id),
	constraint fk_data_budget_record_organisasi_04 foreign key (common_id) references data_master_organisasi (id),
	constraint fk_data_budget_record_organisasi_05 foreign key (jadwal_id, skpd_id) references data_budget_record_organisasi (jadwal_id, common_id),
	constraint fk_data_budget_record_organisasi_06 foreign key (head_id) references data_user (id),
	constraint fk_data_budget_record_organisasi_07 foreign key (jadwal_id) references data_budget_jadwal (id),
	constraint fk_data_budget_record_organisasi_08 foreign key (created_by) references data_user (id),
	constraint fk_data_budget_record_organisasi_09 foreign key (updated_by) references data_user (id),
	constraint fk_data_budget_record_organisasi_10 foreign key (deleted_by) references data_user (id),
	constraint uk_data_budget_record_organisasi_01 unique key (jadwal_id, common_id),
	constraint uk_data_budget_record_organisasi_02 unique key (jadwal_id, skpd_id, unit_id),
	primary key (id)
) engine = innodb
  charset = utf8mb4
  collate = utf8mb4_unicode_ci;