create or replace table data_budget_record_tapd_sign (
	common_id    varchar(21)  not null,
	number       smallint     null,
	position     varchar(255) null,
	name         varchar(255) not null,
	title_prefix varchar(255) null,
	title_suffix varchar(255) null,
	is_locked    bit          not null,
	locked_at    datetime     null,
	locked_by    varchar(18)  null,
	created_at   datetime     null,
	created_by   varchar(18)  null,
	updated_at   datetime     null,
	updated_by   varchar(18)  null,
	is_deleted   bit          null,
	deleted_at   datetime     null,
	deleted_by   varchar(18)  null,
	team_id      varchar(18)  not null,
	id           varchar(255) not null,
	jadwal_id    bigint       not null,
	constraint ck_data_budget_record_tapd_sign_01 check (id = concat_ws('|', jadwal_id, common_id)),
	constraint fk_data_budget_record_tapd_sign_01 foreign key (common_id) references data_master_tapd_sign (id),
	constraint fk_data_budget_record_tapd_sign_02 foreign key (team_id) references data_user (id),
	constraint fk_data_budget_record_tapd_sign_03 foreign key (team_id) references data_master_tapd_team (id),
	constraint fk_data_budget_record_tapd_sign_04 foreign key (locked_by) references data_user (id),
	constraint fk_data_budget_record_tapd_sign_05 foreign key (jadwal_id) references data_budget_jadwal (id),
	constraint fk_data_budget_record_tapd_sign_06 foreign key (created_by) references data_user (id),
	constraint fk_data_budget_record_tapd_sign_07 foreign key (updated_by) references data_user (id),
	constraint fk_data_budget_record_tapd_sign_08 foreign key (deleted_by) references data_user (id),
	constraint uk_data_budget_record_tapd_sign_01 unique key (jadwal_id, common_id),
	primary key (id)
) engine = innodb
  charset = utf8mb4
  collate = utf8mb4_unicode_ci;