package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pembiayaan.pembiayaan4;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan4.DataMasterRekeningPembiayaan4;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pembiayaan.pembiayaan4.DataMasterRekeningPembiayaan4Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening4.DataMasterRekening4JpaRepository;

public interface DataMasterRekeningPembiayaan4JpaRepository extends DataMasterRekening4JpaRepository<DataMasterRekeningPembiayaan4Entity, DataMasterRekeningPembiayaan4> {

}