package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pembiayaan.pembiayaan4;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan4.DataMasterRekeningPembiayaan4;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan4.SipdMasterRekeningPembiayaan4;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pembiayaan.pembiayaan4.SipdMasterRekeningPembiayaan4Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pembiayaan.pembiayaan4.SipdMasterRekeningPembiayaan4Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening4.AbstractSipdMasterRekening4Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening4.SipdMasterRekening4JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class SipdMasterRekeningPembiayaan4RepositoryImpl extends AbstractSipdMasterRekening4Repository<SipdMasterRekeningPembiayaan4Entity, SipdMasterRekeningPembiayaan4, DataMasterRekeningPembiayaan4> implements SipdMasterRekeningPembiayaan4Repository {

	private final SipdMasterRekeningPembiayaan4JpaRepository repository;

	@Override
	protected SipdMasterRekening4JpaRepository<SipdMasterRekeningPembiayaan4Entity, SipdMasterRekeningPembiayaan4, DataMasterRekeningPembiayaan4> repositoryOfMasterRekening() {
		return this.repository;
	}

}