package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pembiayaan.pembiayaan4;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan4.DataMasterRekeningPembiayaan4;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan4.SipdMasterRekeningPembiayaan4;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pembiayaan.pembiayaan4.SipdMasterRekeningPembiayaan4Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening4.SipdMasterRekening4JpaRepository;

public interface SipdMasterRekeningPembiayaan4JpaRepository extends SipdMasterRekening4JpaRepository<SipdMasterRekeningPembiayaan4Entity, SipdMasterRekeningPembiayaan4, DataMasterRekeningPembiayaan4> {

}