package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pembiayaan.pembiayaan5;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan5.DataMasterRekeningPembiayaan5;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan5.SipdMasterRekeningPembiayaan5;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pembiayaan.pembiayaan5.SipdMasterRekeningPembiayaan5Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pembiayaan.pembiayaan5.SipdMasterRekeningPembiayaan5Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening5.AbstractSipdMasterRekening5Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening5.SipdMasterRekening5JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class SipdMasterRekeningPembiayaan5RepositoryImpl extends AbstractSipdMasterRekening5Repository<SipdMasterRekeningPembiayaan5Entity, SipdMasterRekeningPembiayaan5, DataMasterRekeningPembiayaan5> implements SipdMasterRekeningPembiayaan5Repository {

	private final SipdMasterRekeningPembiayaan5JpaRepository repository;

	@Override
	protected SipdMasterRekening5JpaRepository<SipdMasterRekeningPembiayaan5Entity, SipdMasterRekeningPembiayaan5, DataMasterRekeningPembiayaan5> repositoryOfMasterRekening() {
		return this.repository;
	}

}