insert into keuangan_dev.data_budget_common_income_pembiayaan_rincian (id, skpd_id, unit_id, urusan_id, bidang_id, rekening1_id, rekening2_id, rekening3_id, rekening4_id, rekening5_id, rekening6_id, description, information, volume1, satuan1, volume2, satuan2, volume3, satuan3, volume4, satuan4, volume, satuan, price, sebelum, total, created_at, created_by, updated_at, updated_by, is_deleted, deleted_at, deleted_by)
select *
from (
	select id             as id
		 , kode_skpd      as skpd_id
		 , kode_unit      as unit_id
		 , kode_urusan    as urusan_id
		 , kode_bidang    as bidang_id
		 , kode_rekening1 as rekening1_id
		 , kode_rekening2 as rekening2_id
		 , kode_rekening3 as rekening3_id
		 , kode_rekening4 as rekening4_id
		 , kode_rekening5 as rekening5_id
		 , kode_rekening6 as rekening6_id
		 , uraian         as description
		 , keterangan     as information
		 , volume_1       as volume1
		 , satuan_1       as satuan1
		 , volume_2       as volume2
		 , satuan_2       as satuan2
		 , volume_3       as volume3
		 , satuan_3       as satuan3
		 , volume_4       as volume4
		 , satuan_4       as satuan4
		 , 1              as volume
		 , 'Tahun'        as satuan
		 , harga          as price
		 , total          as total
		 , 0              as sebelum
		 , created_at     as created_at
		 , created_by     as created_by
		 , updated_at     as updated_at
		 , updated_by     as updated_by
		 , is_deleted     as is_deleted
		 , deleted_at     as deleted_at
		 , deleted_by     as deleted_by
	from espresso_2025_preproduction.data_penganggaran_penerimaan_pembiayaan_rincian
) t
on duplicate key update skpd_id      = t.skpd_id
                      , unit_id      = t.unit_id
                      , urusan_id    = t.urusan_id
                      , bidang_id    = t.bidang_id
                      , rekening1_id = t.rekening1_id
                      , rekening2_id = t.rekening2_id
                      , rekening3_id = t.rekening3_id
                      , rekening4_id = t.rekening4_id
                      , rekening5_id = t.rekening5_id
                      , rekening6_id = t.rekening6_id
                      , description  = t.description
                      , information  = t.information
                      , volume1      = t.volume1
                      , satuan1      = t.satuan1
                      , volume2      = t.volume2
                      , satuan2      = t.satuan2
                      , volume3      = t.volume3
                      , satuan3      = t.satuan3
                      , volume4      = t.volume4
                      , satuan4      = t.satuan4
                      , volume       = t.volume
                      , satuan       = t.satuan
                      , price        = t.price
                      , total        = t.total
                      , sebelum      = t.sebelum
                      , created_at   = t.created_at
                      , created_by   = t.created_by
                      , updated_at   = t.updated_at
                      , updated_by   = t.updated_by
                      , is_deleted   = t.is_deleted
                      , deleted_at   = t.deleted_at
                      , deleted_by   = t.deleted_by