package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pendapatan_lo.pendapatan_lo3;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo3.DataMasterRekeningPendapatanLo3;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pendapatan_lo.pendapatan_lo3.DataMasterRekeningPendapatanLo3Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo3.DataMasterRekeningPendapatanLo3Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening3.AbstractDataMasterRekening3Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening3.DataMasterRekening3JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class DataMasterRekeningPendapatanLo3RepositoryImpl extends AbstractDataMasterRekening3Repository<DataMasterRekeningPendapatanLo3Entity, DataMasterRekeningPendapatanLo3> implements DataMasterRekeningPendapatanLo3Repository {

	private final DataMasterRekeningPendapatanLo3JpaRepository repository;

	@Override
	protected DataMasterRekening3JpaRepository<DataMasterRekeningPendapatanLo3Entity, DataMasterRekeningPendapatanLo3> repositoryOfMasterRekening() {
		return this.repository;
	}

}