package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pembiayaan.pembiayaan6;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan6.DataMasterRekeningPembiayaan6;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan6.SipdMasterRekeningPembiayaan6;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pembiayaan.pembiayaan6.SipdMasterRekeningPembiayaan6Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pembiayaan.pembiayaan6.SipdMasterRekeningPembiayaan6Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening6.AbstractSipdMasterRekening6Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening6.SipdMasterRekening6JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class SipdMasterRekeningPembiayaan6RepositoryImpl extends AbstractSipdMasterRekening6Repository<SipdMasterRekeningPembiayaan6Entity, SipdMasterRekeningPembiayaan6, DataMasterRekeningPembiayaan6> implements SipdMasterRekeningPembiayaan6Repository {

	private final SipdMasterRekeningPembiayaan6JpaRepository repository;

	@Override
	protected SipdMasterRekening6JpaRepository<SipdMasterRekeningPembiayaan6Entity, SipdMasterRekeningPembiayaan6, DataMasterRekeningPembiayaan6> repositoryOfMasterRekening() {
		return this.repository;
	}

}