package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pembiayaan.pembiayaan6;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan6.DataMasterRekeningPembiayaan6;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan6.SipdMasterRekeningPembiayaan6;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pembiayaan.pembiayaan6.SipdMasterRekeningPembiayaan6Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening6.SipdMasterRekening6JpaRepository;

public interface SipdMasterRekeningPembiayaan6JpaRepository extends SipdMasterRekening6JpaRepository<SipdMasterRekeningPembiayaan6Entity, SipdMasterRekeningPembiayaan6, DataMasterRekeningPembiayaan6> {

}