package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pembiayaan.pembiayaan1;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan1.DataMasterRekeningPembiayaan1;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan1.SipdMasterRekeningPembiayaan1;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pembiayaan.pembiayaan1.SipdMasterRekeningPembiayaan1Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening1.SipdMasterRekening1JpaRepository;

public interface SipdMasterRekeningPembiayaan1JpaRepository extends SipdMasterRekening1JpaRepository<SipdMasterRekeningPembiayaan1Entity, SipdMasterRekeningPembiayaan1, DataMasterRekeningPembiayaan1> {

}