package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pembiayaan.pembiayaan1;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan1.DataMasterRekeningPembiayaan1;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pembiayaan.pembiayaan1.SipdMasterRekeningPembiayaan1;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pembiayaan.pembiayaan1.SipdMasterRekeningPembiayaan1Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pembiayaan.pembiayaan1.SipdMasterRekeningPembiayaan1Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening1.AbstractSipdMasterRekening1Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening1.SipdMasterRekening1JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class SipdMasterRekeningPembiayaan1RepositoryImpl extends AbstractSipdMasterRekening1Repository<SipdMasterRekeningPembiayaan1Entity, SipdMasterRekeningPembiayaan1, DataMasterRekeningPembiayaan1> implements SipdMasterRekeningPembiayaan1Repository {

	private final SipdMasterRekeningPembiayaan1JpaRepository repository;

	@Override
	protected SipdMasterRekening1JpaRepository<SipdMasterRekeningPembiayaan1Entity, SipdMasterRekeningPembiayaan1, DataMasterRekeningPembiayaan1> repositoryOfMasterRekening() {
		return this.repository;
	}

}