create or replace table data_master_kelompok (
	id           varchar(17)  not null,
	code         varchar(17)  not null,
	name         varchar(510) not null,
	type         tinyint      null,
	level        tinyint      not null,
	is_locked    bit          not null,
	locked_at    datetime     null,
	locked_by    varchar(18)  null,
	created_at   datetime     null,
	created_by   varchar(18)  null,
	updated_at   datetime     null,
	updated_by   varchar(18)  null,
	is_deleted   bit          null,
	deleted_at   datetime     null,
	deleted_by   varchar(18)  null,
	kelompok1_id varchar(1)   null,
	kelompok2_id varchar(3)   null,
	kelompok3_id varchar(6)   null,
	kelompok4_id varchar(9)   null,
	kelompok5_id varchar(12)  null,
	kelompok6_id varchar(17)  null,
	constraint ck_data_master_kelompok_01 check (id = code),
	constraint ck_data_master_kelompok_02 check (code = coalesce(kelompok6_id, kelompok5_id, kelompok4_id, kelompok3_id, kelompok2_id, kelompok1_id)),
	constraint ck_data_master_kelompok_03 check (level = (case when kelompok6_id is not null then 6 when kelompok5_id is not null then 5 when kelompok4_id is not null then 4 when kelompok3_id is not null then 3 when kelompok2_id is not null then 2 when kelompok1_id is not null then 1 end)),
	constraint ck_data_master_kelompok_04 check (kelompok1_id = left(id, length(kelompok1_id))),
	constraint ck_data_master_kelompok_05 check (kelompok2_id = left(id, length(kelompok2_id))),
	constraint ck_data_master_kelompok_06 check (kelompok3_id = left(id, length(kelompok3_id))),
	constraint ck_data_master_kelompok_07 check (kelompok4_id = left(id, length(kelompok4_id))),
	constraint ck_data_master_kelompok_08 check (kelompok5_id = left(id, length(kelompok5_id))),
	constraint ck_data_master_kelompok_09 check (kelompok6_id = left(id, length(kelompok6_id))),
	constraint fk_data_master_kelompok_01 foreign key (locked_by) references data_user (id),
	constraint fk_data_master_kelompok_02 foreign key (created_by) references data_user (id),
	constraint fk_data_master_kelompok_03 foreign key (updated_by) references data_user (id),
	constraint fk_data_master_kelompok_04 foreign key (deleted_by) references data_user (id),
	primary key (id)
) engine = innodb
  charset = utf8mb4
  collate = utf8mb4_unicode_ci;