create or replace table data_budget_jadwal (
	id             bigint       not null auto_increment,
	year           smallint     not null,
	name           varchar(255) not null,
	from_time      datetime     null,
	into_time      datetime     null,
	is_perda       bit          not null,
	perda_date     date         null,
	perda_number   varchar(255) null,
	is_perkada     bit          not null,
	perkada_date   date         null,
	perkada_number varchar(255) null,
	is_locked      bit          not null,
	locked_at      datetime     null,
	locked_by      varchar(18)  null,
	created_at     datetime     null,
	created_by     varchar(18)  null,
	updated_at     datetime     null,
	updated_by     varchar(18)  null,
	is_deleted     bit          null,
	deleted_at     datetime     null,
	deleted_by     varchar(18)  null,
	tahapan_id     bigint       not null,
	rkpd_id        bigint       null,
	ppas_id        bigint       null,
	apbd_id        bigint       null,
	sipd_id        bigint       null,
	constraint fk_data_budget_jadwal_01 foreign key (rkpd_id) references data_budget_jadwal (id),
	constraint fk_data_budget_jadwal_02 foreign key (ppas_id) references data_budget_jadwal (id),
	constraint fk_data_budget_jadwal_03 foreign key (apbd_id) references data_budget_jadwal (id),
	constraint fk_data_budget_jadwal_04 foreign key (locked_by) references data_user (id),
	constraint fk_data_budget_jadwal_05 foreign key (created_by) references data_user (id),
	constraint fk_data_budget_jadwal_06 foreign key (updated_by) references data_user (id),
	constraint fk_data_budget_jadwal_07 foreign key (deleted_by) references data_user (id),
	primary key (id)
) engine = innodb
  charset = utf8mb4
  collate = utf8mb4_unicode_ci;