create or replace table data_budget_common_income_pendapatan_rekening (
	id           varchar(255)   not null,
	skpd_id      varchar(22)    not null,
	unit_id      varchar(22)    not null,
	urusan_id    varchar(1)     not null,
	bidang_id    varchar(4)     not null,
	rekening1_id varchar(1)     not null,
	rekening2_id varchar(3)     not null,
	rekening3_id varchar(6)     not null,
	rekening4_id varchar(9)     not null,
	rekening5_id varchar(12)    not null,
	rekening6_id varchar(17)    not null,
	total        decimal(38, 2) not null,
	sebelum      decimal(38, 2) not null,
	created_at   datetime       null,
	created_by   varchar(18)    null,
	updated_at   datetime       null,
	updated_by   varchar(18)    null,
	is_deleted   bit            null,
	deleted_at   datetime       null,
	deleted_by   varchar(18)    null,
	constraint ck_data_budget_common_income_pendapatan_rekening_01 check (id = concat_ws('|', unit_id, bidang_id, rekening6_id)),
	constraint fk_data_budget_common_income_pendapatan_rekening_01 foreign key (rekening1_id) references data_master_pendapatan1 (id),
	constraint fk_data_budget_common_income_pendapatan_rekening_02 foreign key (rekening1_id, rekening2_id) references data_master_pendapatan2 (rekening1_id, id),
	constraint fk_data_budget_common_income_pendapatan_rekening_03 foreign key (rekening1_id, rekening2_id, rekening3_id) references data_master_pendapatan3 (rekening1_id, rekening2_id, id),
	constraint fk_data_budget_common_income_pendapatan_rekening_04 foreign key (rekening1_id, rekening2_id, rekening3_id, rekening4_id) references data_master_pendapatan4 (rekening1_id, rekening2_id, rekening3_id, id),
	constraint fk_data_budget_common_income_pendapatan_rekening_05 foreign key (rekening1_id, rekening2_id, rekening3_id, rekening4_id, rekening5_id) references data_master_pendapatan5 (rekening1_id, rekening2_id, rekening3_id, rekening4_id, id),
	constraint fk_data_budget_common_income_pendapatan_rekening_06 foreign key (rekening1_id, rekening2_id, rekening3_id, rekening4_id, rekening5_id, rekening6_id) references data_master_pendapatan6 (rekening1_id, rekening2_id, rekening3_id, rekening4_id, rekening5_id, id),
	constraint fk_data_budget_common_income_pendapatan_rekening_07 foreign key (skpd_id) references data_master_organisasi (id),
	constraint fk_data_budget_common_income_pendapatan_rekening_08 foreign key (skpd_id, unit_id) references data_master_organisasi (skpd_id, unit_id),
	constraint fk_data_budget_common_income_pendapatan_rekening_09 foreign key (urusan_id) references data_master_urusan (id),
	constraint fk_data_budget_common_income_pendapatan_rekening_10 foreign key (urusan_id, bidang_id) references data_master_bidang (urusan_id, id),
	constraint fk_data_budget_common_income_pendapatan_rekening_11 foreign key (created_by) references data_user (id),
	constraint fk_data_budget_common_income_pendapatan_rekening_12 foreign key (updated_by) references data_user (id),
	constraint fk_data_budget_common_income_pendapatan_rekening_13 foreign key (deleted_by) references data_user (id),
	primary key (id)
) engine = innodb
  charset = utf8mb4
  collate = utf8mb4_unicode_ci;