package com.rendyrobbani.keuangan.persistence.repository.budget.common.ie.income.pendapatan.rekening;

import com.rendyrobbani.keuangan.core.domain.entity.budget.common.ie.income.pendapatan.rekening.DataBudgetCommonIncomePendapatanRekening;
import com.rendyrobbani.keuangan.persistence.entity.budget.common.ie.income.pendapatan.rekening.DataBudgetCommonIncomePendapatanRekeningEntity;
import com.rendyrobbani.keuangan.persistence.repository.budget.common.ie.DataBudgetCommonRekeningJpaRepository;

public interface DataBudgetCommonIncomePendapatanRekeningJpaRepository extends DataBudgetCommonRekeningJpaRepository<DataBudgetCommonIncomePendapatanRekeningEntity, DataBudgetCommonIncomePendapatanRekening> {

}