package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.kewajiban.kewajiban6;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.kewajiban.kewajiban6.DataMasterRekeningKewajiban6;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.kewajiban.kewajiban6.DataMasterRekeningKewajiban6Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening6.DataMasterRekening6JpaRepository;

public interface DataMasterRekeningKewajiban6JpaRepository extends DataMasterRekening6JpaRepository<DataMasterRekeningKewajiban6Entity, DataMasterRekeningKewajiban6> {

}