package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.kewajiban.kewajiban6;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.kewajiban.kewajiban6.DataMasterRekeningKewajiban6;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.kewajiban.kewajiban6.SipdMasterRekeningKewajiban6;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.kewajiban.kewajiban6.SipdMasterRekeningKewajiban6Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening6.SipdMasterRekening6JpaRepository;

public interface SipdMasterRekeningKewajiban6JpaRepository extends SipdMasterRekening6JpaRepository<SipdMasterRekeningKewajiban6Entity, SipdMasterRekeningKewajiban6, DataMasterRekeningKewajiban6> {

}