package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pendapatan.pendapatan2;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan.pendapatan2.DataMasterRekeningPendapatan2;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pendapatan.pendapatan2.DataMasterRekeningPendapatan2Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening2.DataMasterRekening2JpaRepository;

public interface DataMasterRekeningPendapatan2JpaRepository extends DataMasterRekening2JpaRepository<DataMasterRekeningPendapatan2Entity, DataMasterRekeningPendapatan2> {

}