package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pendapatan_lo.pendapatan_lo4;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo4.DataMasterRekeningPendapatanLo4;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pendapatan_lo.pendapatan_lo4.DataMasterRekeningPendapatanLo4Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo4.DataMasterRekeningPendapatanLo4Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening4.AbstractDataMasterRekening4Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening4.DataMasterRekening4JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class DataMasterRekeningPendapatanLo4RepositoryImpl extends AbstractDataMasterRekening4Repository<DataMasterRekeningPendapatanLo4Entity, DataMasterRekeningPendapatanLo4> implements DataMasterRekeningPendapatanLo4Repository {

	private final DataMasterRekeningPendapatanLo4JpaRepository repository;

	@Override
	protected DataMasterRekening4JpaRepository<DataMasterRekeningPendapatanLo4Entity, DataMasterRekeningPendapatanLo4> repositoryOfMasterRekening() {
		return this.repository;
	}

}