package com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.type.pendapatan_lo.pendapatan_lo4;

import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo4.DataMasterRekeningPendapatanLo4;
import com.rendyrobbani.keuangan.core.domain.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo4.SipdMasterRekeningPendapatanLo4;
import com.rendyrobbani.keuangan.core.domain.repository.master.classification.rekening.type.pendapatan_lo.pendapatan_lo4.SipdMasterRekeningPendapatanLo4Repository;
import com.rendyrobbani.keuangan.persistence.entity.master.classification.rekening.type.pendapatan_lo.pendapatan_lo4.SipdMasterRekeningPendapatanLo4Entity;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening4.AbstractSipdMasterRekening4Repository;
import com.rendyrobbani.keuangan.persistence.repository.master.classification.rekening.base.rekening4.SipdMasterRekening4JpaRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class SipdMasterRekeningPendapatanLo4RepositoryImpl extends AbstractSipdMasterRekening4Repository<SipdMasterRekeningPendapatanLo4Entity, SipdMasterRekeningPendapatanLo4, DataMasterRekeningPendapatanLo4> implements SipdMasterRekeningPendapatanLo4Repository {

	private final SipdMasterRekeningPendapatanLo4JpaRepository repository;

	@Override
	protected SipdMasterRekening4JpaRepository<SipdMasterRekeningPendapatanLo4Entity, SipdMasterRekeningPendapatanLo4, DataMasterRekeningPendapatanLo4> repositoryOfMasterRekening() {
		return this.repository;
	}

}